---
name: 🐛 Bug Report
description: Report a bug or unexpected behavior in emp3r0r
title: "[BUG] "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please provide as much detail as possible to help us reproduce and fix the issue.

        **Note**: For security vulnerabilities, please follow our security policy and report privately.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm the following before submitting a bug report
      options:
        - label: I have read the documentation
          required: true
        - label: I have searched existing issues for duplicates
          required: true
        - label: This is not a question (use the question template instead)
          required: true
        - label: I can reproduce this issue consistently
          required: true

  - type: input
    id: version
    attributes:
      label: emp3r0r Version
      description: What version of emp3r0r are you using?
      placeholder: "e.g., v2.4.0, latest commit hash, or 'built from source' (which commit?)"
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - C2 Server
        - Agent
        - Modules
        - Installation/Build
        - Documentation
        - Other/Unknown
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please run the commands below and paste the output
      placeholder: |
        Run these commands and paste the output:

        ```bash
        # OS and kernel information
        uname -a

        # OS release information
        cat /etc/os-release 2>/dev/null || sw_vers 2>/dev/null || systeminfo | findstr /B /C:"OS Name" /C:"OS Version"

        # Architecture
        uname -m

        # Go version (if building from source)
        go version

        # emp3r0r version
        ./emp3r0r -version 2>/dev/null || ./core/emp3r0r -version 2>/dev/null || echo "emp3r0r version: [paste version here]"

        # Additional info (if relevant):
        # - Network setup: 
        # - Virtualization: 
        # - Container runtime: docker version / podman version
        ```
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: "When I do X, Y happens instead of Z..."
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior
      placeholder: |
        1. Start emp3r0r with configuration...
        2. Run command...
        3. Observe that...
        4. Expected vs actual behavior...
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: "I expected..."
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: "Instead, what happened was..."
    validations:
      required: true

  - type: textarea
    id: logs-output
    attributes:
      label: Logs and Output
      description: Relevant logs, error messages, or output
      placeholder: |
        Paste relevant logs here. Use ``` code blocks for formatting.

        Remember to redact any sensitive information!
      render: text

  - type: textarea
    id: configuration
    attributes:
      label: Configuration
      description: Relevant configuration details (redact sensitive info)
      placeholder: |
        Share relevant parts of your configuration files, command line arguments, etc.

        ⚠️ Make sure to remove any sensitive information like passwords, API keys, etc.
      render: text

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context about the problem
      placeholder: |
        - Screenshots (if applicable)
        - Workarounds you've tried
        - Related issues
        - Network topology
        - Timeline of when the issue started
        - Any other relevant information

  - type: dropdown
    id: impact
    attributes:
      label: Impact
      description: How severe is this bug?
      options:
        - Critical - Complete system failure
        - High - Major functionality broken
        - Medium - Some features affected
        - Low - Minor inconvenience
        - Cosmetic - UI/display issues
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to help?
      options:
        - label: I am willing to submit a pull request to fix this bug
        - label: I can help test the fix once available
        - label: I can provide additional debugging information if needed
