blank_issues_enabled: false
contact_links:
  - name: 📖 Documentation
    url: https://github.com/jm33-m0/emp3r0r/blob/master/README.md
    about: Check the documentation for usage guides and FAQ
  - name: 💬 Discussions
    url: https://github.com/jm33-m0/emp3r0r/discussions
    about: Ask questions and discuss features with the community
  - name: 🔒 Security Issues
    url: https://github.com/jm33-m0/emp3r0r/security/policy
    about: Report security vulnerabilities privately (do not create public issues for security bugs)
  - name: 📋 Project Board
    url: https://github.com/jm33-m0/emp3r0r/projects
    about: Track the development progress and roadmap
