---
name: 📚 Documentation Issue
description: Report an issue with documentation or suggest documentation improvements
title: "[DOCS] "
labels: ["documentation", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve emp3r0r's documentation! Clear documentation helps everyone.

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation issue is this?
      options:
        - Missing documentation
        - Incorrect/outdated information
        - Unclear instructions
        - Typo/grammar error
        - Code example issue
        - Broken link
        - Translation issue
        - Improvement suggestion
    validations:
      required: true

  - type: input
    id: doc-location
    attributes:
      label: Documentation Location
      description: Where is the documentation issue located?
      placeholder: "e.g., README.md, wiki page URL, specific file path..."
    validations:
      required: true

  - type: textarea
    id: issue-description
    attributes:
      label: Issue Description
      description: Clearly describe the documentation issue
      placeholder: "The documentation states... but it should say..."
    validations:
      required: true

  - type: textarea
    id: suggested-fix
    attributes:
      label: Suggested Fix
      description: If you have a suggestion for how to fix this, please describe it
      placeholder: "The documentation should be updated to..."

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context about the documentation issue
      placeholder: "Related issues, links, or additional information..."
