---
name: 🚀 Feature Request
description: Suggest a new feature or enhancement for emp3r0r
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide detailed information about your idea.

        **Note**: Before submitting, please check if a similar feature request already exists.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm the following before submitting a feature request
      options:
        - label: I have read the documentation
          required: true
        - label: I have searched existing issues and feature requests
          required: true
        - label: This is not a bug report (use the bug template instead)
          required: true
        - label: This feature aligns with the project's goals and scope
          required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What category does this feature belong to?
      options:
        - C2 Server Enhancement
        - Agent Capability
        - New Module
        - Communication Protocol
        - User Interface/UX
        - Installation/Deployment
        - Security Enhancement
        - Performance Improvement
        - Documentation
        - Development Tools
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical - Blocks major use cases
        - High - Would significantly improve usability
        - Medium - Nice to have
        - Low - Minor enhancement
    validations:
      required: true

  - type: textarea
    id: feature-summary
    attributes:
      label: Feature Summary
      description: A brief, clear description of the feature you'd like to see
      placeholder: "I would like emp3r0r to have..."
    validations:
      required: true

  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement
      description: |
        Describe the problem this feature would solve and current pain points.
        Help us understand the "why" behind your request by explaining the challenges you face.
      placeholder: |
        Currently, when I try to do X, I face these challenges:
        - Issue 1...
        - Issue 2...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: |
        Describe your ideal solution in detail. What would the feature do?
        How would it work? Be as specific as possible about the functionality you envision.
      placeholder: |
        I propose adding a feature that would:
        - Functionality 1...
        - Functionality 2...
    validations:
      required: true

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: |
        Provide specific examples of how this feature would be used in real scenarios.
        Use the format: "As a [user type], I want to [action] so that [benefit]"
        Include different scenarios where this feature would be valuable.
      placeholder: |
        Use Case 1: As a [user type], I want to [action] so that [benefit]
        Use Case 2: When [scenario], this feature would allow [outcome]
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: |
        What alternatives have you considered? Why aren't current solutions sufficient?
        This helps us understand if there are existing workarounds and why they don't meet your needs.
      placeholder: |
        I considered:
        - Alternative 1: [description] - but this doesn't work because...
        - Current workaround: [description] - but this is problematic because...

  - type: textarea
    id: implementation-ideas
    attributes:
      label: Implementation Ideas
      description: |
        Do you have ideas about how this could be implemented? (Optional)
        Consider technical aspects like platform compatibility, security implications, and performance impact.
        This is helpful but not required - our developers will design the implementation.
      placeholder: |
        This could potentially be implemented by:
        - Adding a new module that...
        - Modifying the existing [component] to...

  - type: textarea
    id: mockups-examples
    attributes:
      label: Mockups/Examples
      description: |
        Provide visual mockups, command examples, or API examples if applicable.
        Show us what the feature would look like in action - this really helps with understanding your vision!
      placeholder: |
        Command example:
        emp3r0r> new_feature --option value

        Expected output:
        Feature working as expected...
      render: text

  - type: checkboxes
    id: breaking-changes
    attributes:
      label: Breaking Changes
      description: Consider the impact of this feature
      options:
        - label: This feature could introduce breaking changes to existing functionality
        - label: This feature requires changes to configuration format
        - label: This feature affects the agent-server communication protocol
        - label: This feature would require database schema changes

  - type: dropdown
    id: target-users
    attributes:
      label: Target Users
      description: Who would primarily benefit from this feature?
      options:
        - Penetration Testers
        - Red Team Operators
        - Security Researchers
        - Malware Analysts
        - System Administrators
        - Developers/Contributors
        - All Users
        - Other (specify in additional context)
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: |
        Any other relevant information that would help us understand and implement this feature:
        - Links to related tools/features in other projects
        - References to documentation or standards  
        - Screenshots or examples from other tools
        - Timeline considerations or urgency
        - Resource requirements or constraints
      placeholder: "Any additional context, links, or relevant information..."

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to help with this feature?
      options:
        - label: I am willing to submit a pull request to implement this feature
        - label: I can help with design/planning discussions
        - label: I can help with testing once implemented
        - label: I can provide additional requirements/feedback during development
