---

name: 🚀 Feature Request
description: Suggest a new feature or enhancement for emp3r0r
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]
body:

- type: markdown
  attributes:
  value: |
  Thanks for taking the time to suggest a new feature! Please fill out this form to help us understand your request.

      ⚠️ **Issues not using this template will be closed.**

- type: checkboxes
  id: prerequisites
  attributes:
  label: Prerequisites
  description: Please confirm the following before submitting your feature request
  options: - label: I have searched existing issues to ensure this feature hasn't been requested
  required: true - label: I have checked the documentation to ensure this feature doesn't already exist
  required: true - label: This feature aligns with the project's goals and scope
  required: true

- type: dropdown
  id: request-type
  attributes:
  label: Feature Type
  description: What type of feature request is this?
  options: - New functionality - Enhancement to existing feature - Performance improvement - Security improvement - Documentation improvement - Developer experience improvement - Other
  validations:
  required: true

- type: checkboxes
  id: problem-relation
  attributes:
  label: Is this feature request related to a problem?
  options: - label: "No, it's just a proposal for a new feature" - label: "Yes, it addresses a current limitation or problem"

- type: textarea
  id: problem-description
  attributes:
  label: Problem Description
  description: If this feature is related to a problem, please describe it clearly
  placeholder: "I'm always frustrated when... / The current limitation is..."

- type: textarea
  id: feature-description
  attributes:
  label: Describe the Feature
  description: A clear and concise description of what you want to happen
  placeholder: "I would like emp3r0r to..."
  validations:
  required: true

- type: textarea
  id: use-cases
  attributes:
  label: Use Cases
  description: Describe specific scenarios where this feature would be useful
  placeholder: | 1. When performing... 2. During... 3. For...
  validations:
  required: true

- type: textarea
  id: proposed-solution
  attributes:
  label: Proposed Solution
  description: How do you envision this feature working?
  placeholder: "This could be implemented by..."

- type: textarea
  id: alternatives
  attributes:
  label: Alternatives Considered
  description: Have you considered any alternative solutions or workarounds?
  placeholder: "I've considered... / Alternative approaches might include..."

- type: dropdown
  id: priority
  attributes:
  label: Priority Level
  description: How important is this feature to you?
  options: - Low - Nice to have - Medium - Would improve workflow - High - Blocking current tasks - Critical - Essential for project use
  validations:
  required: true

- type: checkboxes
  id: affected-components
  attributes:
  label: Affected Components
  description: Which parts of emp3r0r would this feature affect?
  options: - label: Agent - label: Command & Control (CC) - label: Communication/Transport - label: Modules - label: Web UI - label: Documentation - label: Build system - label: Other (please specify in additional context)

- type: checkboxes
  id: target-platforms
  attributes:
  label: Target Platforms
  description: Which platforms should this feature support?
  options: - label: Linux - label: Windows - label: All platforms - label: Platform-specific (please specify in additional context)

- type: textarea
  id: additional-context
  attributes:
  label: Additional Context
  description: Add any other context, mockups, examples, or references about the feature request
  placeholder: "Any additional information, links to similar features, mockups, etc..."

- type: checkboxes
  id: contribution
  attributes:
  label: Contribution
  description: Are you willing to contribute to implementing this feature?
  options: - label: "Yes, I can help implement this feature" - label: "Yes, I can help with testing" - label: "Yes, I can help with documentation" - label: "No, but I'd be happy to provide feedback during development"
