---
name: ❓ Question/Help
description: Ask a question about using emp3r0r
title: "[QUESTION] "
labels: ["question", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your question! Please check the documentation and existing discussions first.

        **Note**: For general discussions, consider using [GitHub Discussions](https://github.com/jm33-m0/emp3r0r/discussions) instead.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: Please confirm the following before asking your question
      options:
        - label: I have read the documentation
          required: true
        - label: I have searched existing issues and discussions
          required: true
        - label: This is not a bug report (use the bug template instead)
          required: true

  - type: dropdown
    id: question-category
    attributes:
      label: Question Category
      description: What category does your question fall into?
      options:
        - Installation/Setup
        - Configuration
        - Usage/How-to
        - Troubleshooting
        - Best practices
        - Security considerations
        - Performance
        - Development/Contributing
        - Other
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: Clearly describe what you want to know or what you're trying to achieve
      placeholder: "I'm trying to... but I don't understand how to..."
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide context about your setup, what you've tried, etc.
      placeholder: |
        - What I'm trying to achieve:
        - What I've tried so far:
        - Current setup/environment:
        - Any error messages:

  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: Any other relevant information
      placeholder: "Links, screenshots, configuration details, etc..."
